### ISSUE TITLE
ebook results empty

### ISSUE THREAD

**Issue by obar1** [McPatate/orly_book_extractor#1]
empty ebook
Spark: The Definitive Guide_9781491912201.epub'
![image](https://user-images.githubusercontent.com/387386/68543274-4502d980-03b5-11ea-9e76-9fcdb3de8556.png)

**Comment by McPatate** [comment]
Hi @obar1,
I'd advise you delete your image from github and/or change your password !
Try not sharing this info in your screenshot next time.
As for the issue, it's fixed now. The book you get has content and minimal styling.
Links are broken though. I am currently working on fixing links and getting a pretty epub.
Thank you for testing my code !
